# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeprato', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('modopreparo', models.TextField()),
                ('qtdpessoas', models.IntegerField()),
                ('tempopreparo', models.IntegerField()),
            ],
        ),
    ]
