# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='imagem',
            field=models.CharField(default='null.jpg', max_length=200),
        ),
    ]
