# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receitas_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='imagem',
            field=models.CharField(default='/static/images/null.jpg', max_length=200),
        ),
    ]
